#!/usr/bin/env bash
# standup-seed.sh — generates daily standup context file for IDEA agents
# Runs at 07:30 CET Mon–Fri via Pi system cron.
# Writes standups/YYYY-MM-DD.md at the org root.
# If context unchanged since yesterday, marks standup as skipped — no agents are woken.
# Monday: always runs regardless of hash (start-of-week context).

set -euo pipefail

IDEA_DIR="/home/pi/idea"
STANDUPS_DIR="$IDEA_DIR/standups"
HASH_FILE="$STANDUPS_DIR/.last-context-hash"
TODAY=$(date +"%Y-%m-%d")
TIME_NOW=$(date +"%H:%M")
STANDUP_FILE="$STANDUPS_DIR/$TODAY.md"
LOG_TAG="[standup-seed $TODAY]"

AGENT_REPOS=(
  "agents/agent-operations-manager"
  "agents/agent-engine-dev"
  "agents/agent-console-dev"
  "agents/agent-site-dev"
  "agents/agent-programme-manager"
)

echo "$LOG_TAG Starting"
mkdir -p "$STANDUPS_DIR"

# Monday: always run
DOW=$(date +%u)
FORCE_RUN=false
[[ "$DOW" == "1" ]] && FORCE_RUN=true && echo "$LOG_TAG Monday — forcing run"

# ── Collect context ──────────────────────────────────────────────────────────

CONTEXT_PARTS=()

# 1. Commits since yesterday per repo
COMMIT_LINES=""
for REPO in "${AGENT_REPOS[@]}"; do
  REPO_PATH="$IDEA_DIR/$REPO"
  REPO_NAME=$(basename "$REPO")
  if [[ -d "$REPO_PATH/.git" ]]; then
    COMMITS=$(git -C "$REPO_PATH" log --oneline --since="yesterday 07:00" 2>/dev/null || true)
    if [[ -n "$COMMITS" ]]; then
      COMMIT_LINES+="$REPO_NAME: $COMMITS"$'\n'
    fi
  fi
done
CONTEXT_PARTS+=("COMMITS:${COMMIT_LINES}")

# 2. BACKLOG.md fingerprint
if [[ -f "$IDEA_DIR/BACKLOG.md" ]]; then
  BL_HASH=$(sha256sum "$IDEA_DIR/BACKLOG.md" | awk '{print $1}')
  CONTEXT_PARTS+=("BACKLOG:$BL_HASH")
fi

# 3. Open PRs via gh CLI (graceful if unavailable or no auth)
PR_LINES=""
if command -v gh &>/dev/null; then
  for REPO in "${AGENT_REPOS[@]}"; do
    REPO_NAME=$(basename "$REPO")
    PRS=$(gh pr list --repo "koenswings/$REPO_NAME" --state open \
          --json number,title,createdAt \
          --template '{{range .}}#{{.number}}:{{.title}}:{{.createdAt}}{{"\n"}}{{end}}' \
          2>/dev/null || true)
    [[ -n "$PRS" ]] && PR_LINES+="$REPO_NAME: $PRS"$'\n'
  done
fi
CONTEXT_PARTS+=("PRS:$PR_LINES")

# 4. New files in proposals/ and discussions/
NEW_FILES=""
for DIR_NAME in "proposals" "discussions"; do
  DIR_PATH="$IDEA_DIR/$DIR_NAME"
  if [[ -d "$DIR_PATH" ]]; then
    NEWER=$( [[ -f "$HASH_FILE" ]] && find "$DIR_PATH" -name "*.md" -newer "$HASH_FILE" -printf "%f\n" 2>/dev/null | sort || true )
    [[ -n "$NEWER" ]] && NEW_FILES+="$DIR_NAME: $NEWER"$'\n'
  fi
done
CONTEXT_PARTS+=("NEW_FILES:$NEW_FILES")

# ── Hash check ───────────────────────────────────────────────────────────────

CONTEXT_STRING=$(printf '%s\n' "${CONTEXT_PARTS[@]}")
CURRENT_HASH=$(echo "$CONTEXT_STRING" | sha256sum | awk '{print $1}')
STORED_HASH=$( [[ -f "$HASH_FILE" ]] && cat "$HASH_FILE" || echo "" )

if [[ "$CURRENT_HASH" == "$STORED_HASH" ]] && [[ "$FORCE_RUN" == "false" ]]; then
  echo "$LOG_TAG No changes (hash: ${CURRENT_HASH:0:8}). Writing skipped standup."
  cat > "$STANDUP_FILE" <<EOF
# Standup — $TODAY

<!-- Generated by standup-seed.sh at $TIME_NOW -->
<!-- STANDUP_SKIPPED -->

No changes detected since yesterday. Standup skipped — downstream agent jobs will do nothing.
EOF
  cp "$STANDUP_FILE" "$STANDUPS_DIR/LATEST.md"
  cd "$IDEA_DIR"
  git add "standups/$TODAY.md" "standups/LATEST.md" 2>/dev/null || true
  git commit -m "Standup $TODAY: skipped (no changes)" 2>/dev/null || true
  git push 2>/dev/null || true
  echo "$LOG_TAG Done — skipped"
  exit 0
fi

echo "$LOG_TAG Changes detected (hash: ${CURRENT_HASH:0:8}). Writing standup."
echo "$CURRENT_HASH" > "$HASH_FILE"

# ── Build context sections ───────────────────────────────────────────────────

COMMITS_SECTION="### Commits since yesterday"$'\n'
HAS_COMMITS=false
for REPO in "${AGENT_REPOS[@]}"; do
  REPO_PATH="$IDEA_DIR/$REPO"
  REPO_NAME=$(basename "$REPO")
  if [[ -d "$REPO_PATH/.git" ]]; then
    COMMITS=$(git -C "$REPO_PATH" log --oneline --since="yesterday 07:00" 2>/dev/null || true)
    if [[ -n "$COMMITS" ]]; then
      HAS_COMMITS=true
      while IFS= read -r LINE; do
        COMMITS_SECTION+="- **$REPO_NAME**: $LINE"$'\n'
      done <<< "$COMMITS"
    fi
  fi
done
[[ "$HAS_COMMITS" == "false" ]] && COMMITS_SECTION+="- No commits across any repo"$'\n'

PR_SECTION="### Open PRs"$'\n'
HAS_PRS=false
if command -v gh &>/dev/null && [[ -n "$PR_LINES" ]]; then
  HAS_PRS=true
  PR_SECTION+="$PR_LINES"
fi
[[ "$HAS_PRS" == "false" ]] && PR_SECTION+="- No open PRs (or gh CLI not configured)"$'\n'

BL_SECTION="### Backlog snapshot"$'\n'
if [[ -f "$IDEA_DIR/BACKLOG.md" ]]; then
  IN_PROGRESS=$(grep -E "^\- \[.\] .* \| in_progress" "$IDEA_DIR/BACKLOG.md" 2>/dev/null || true)
  INBOX=$(grep -E "^\- \[.\] .* \| inbox" "$IDEA_DIR/BACKLOG.md" 2>/dev/null | head -10 || true)
  [[ -n "$IN_PROGRESS" ]] && BL_SECTION+="**In progress:**"$'\n'"$IN_PROGRESS"$'\n'
  [[ -n "$INBOX" ]] && BL_SECTION+="**Inbox (top 10):**"$'\n'"$INBOX"$'\n'
  [[ -z "$IN_PROGRESS" && -z "$INBOX" ]] && BL_SECTION+="- BACKLOG.md present but no task lines found"$'\n'
else
  BL_SECTION+="- BACKLOG.md not yet generated"$'\n'
fi

NEW_FILES_SECTION=""
if [[ -n "$NEW_FILES" ]]; then
  NEW_FILES_SECTION="### New proposals / discussions"$'\n'"$NEW_FILES"$'\n'
fi

# ── Write standup file ───────────────────────────────────────────────────────

cat > "$STANDUP_FILE" <<EOF
# Standup — $TODAY

<!-- Generated by standup-seed.sh at $TIME_NOW -->
<!-- Context hash: ${CURRENT_HASH:0:8} (changed since last standup) -->

## Context

$COMMITS_SECTION
$PR_SECTION
$BL_SECTION
$NEW_FILES_SECTION
---

<!-- Quality Manager: add ## Summary and ## quality-manager sections below at 07:35 -->
<!-- engine-dev:        add ## engine-dev section at 07:45 -->
<!-- console-dev:       add ## console-dev section at 07:55 -->
<!-- site-dev:          add ## site-dev section at 08:05 -->
<!-- programme-manager: add ## programme-manager section at 08:15 -->

EOF

# ── Commit and push ──────────────────────────────────────────────────────────

cp "$STANDUP_FILE" "$STANDUPS_DIR/LATEST.md"

cd "$IDEA_DIR"
git add "standups/$TODAY.md" "standups/LATEST.md" "standups/.last-context-hash" 2>/dev/null || true
git commit -m "Standup seed: $TODAY" 2>/dev/null || true
git push 2>/dev/null || true

echo "$LOG_TAG Done — standup file ready: $STANDUP_FILE"
